#!/usr/bin/env bash
set -euo pipefail

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

# Disable animations to avoid glitches
ANIMS_ENABLED="$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')" || true
hyprctl -q keyword animations:enabled 0

# Hide windows
show-desktop
# sleep 0.02

# Bail if already locked
if pgrep -x swaylock > /dev/null; then
  exit 0
fi

# Per-output screenshots
mapfile -t outputs < <(hyprctl -j monitors | jq -r '.[].name')
args=()
for out in "${outputs[@]}"; do
  img="$tmpdir/$out.png"
  grim -o "$out" "$img"
  args+=( --image "$out:$img" )
done

# Start swaylock and block here
swaylock -f \
  --clock \
  --indicator \
  --indicator-radius 120 \
  --indicator-thickness 8 \
  --line-color 282A36 \
  --ring-color BD93F9 \
  --inside-color 282A36 \
  --key-hl-color 50FA7B \
  --separator-color 00000000 \
  --text-color F8F8F2 \
  --text-caps-lock-color="" \
  --line-ver-color BD93F9 \
  --ring-ver-color BD93F9 \
  --inside-ver-color 282A36 \
  --text-ver-color 8BE9FD \
  --ring-wrong-color FF5555 \
  --text-wrong-color FF5555 \
  --inside-wrong-color 282A36 \
  --inside-clear-color 282A36 \
  --text-clear-color 8BE9FD \
  --ring-clear-color 8BE9FD \
  --line-clear-color 8BE9FD \
  --line-wrong-color 282A36 \
  --bs-hl-color 8BE9FD \
  --separator-color 00000000 \
  --datestr "%a %e.%m.%Y" \
  --timestr "%H:%M" \
  --font "Fira Mono" \
  --fade-in 0.15 \
  --show-failed-attempts \
  --ignore-empty-password \
  "${args[@]}"

# We are now *unlocked* here

# Restore windows
show-desktop
sleep 0.02

# Re-enable animations
if [ "${ANIMS_ENABLED:-1}" = "1" ]; then
  hyprctl -q keyword animations:enabled 1
fi