#!/usr/bin/env python3

# import websocket
# import json
# import hashlib
# import base64

# ws = websocket.create_connection("ws://localhost:4455")

# # Stop recording
# ws.send(json.dumps({"op": 6, "d": {"requestType": "StopRecord", "requestId": "1"}}))

# # Quit OBS
# ws.send(json.dumps({"op": 6, "d": {"requestType": "Quit", "requestId": "2"}}))

# ws.close()